
name: Build into Executables And Release

on:
  release:
    types: [published]
  workflow_dispatch:
  
jobs:
  BuildAndUploadToReleaseAssets:
    permissions:
        contents: write
    runs-on: windows-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v3
        
        - name: Clone Pyinstaller Repo
          run: |
            gh repo clone pyinstaller/pyinstaller
            dir ./
        
        - name: Setup MinGW-64x
          uses: egor-tensin/setup-mingw@v2
        
        - name: Compile Pyinstaller
          run: python ./waf --gcc all

        - name: Set up Python
          uses: actions/setup-python@v3
          with:
            python-version: 3.11

        - name: Install Requirements
          run: |
            pip install wheel
            pip install ./pyinstaller
            pip install -r requirements.txt
        
        - name: Build with PyInstaller
          run: pyinstaller --clean main.spec --distpath "./Myth Mod Manager"
        
        - name: Zip Myth Mod Manager
          run: tar -a -c -f Myth-Mod-Manager.zip "Myth Mod Manager/Myth Mod Manager.exe"

        - name: Upload Myth Mod Manager to Latest Release Assets
          uses: softprops/action-gh-release@v1
          if: startsWith(github.ref, 'refs/tags/')
          with:
            files: Myth-Mod-Manager.zip