
name: Build Linux And Release

on:
  release:
    types: [published]
  workflow_dispatch:
  
jobs:
  BuildAndUploadToReleaseAssets:
    permissions:
        contents: write
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: 3.11

        - name: Install Requirements
          run: pip install -r requirements.txt
        
        - name: Build with PyInstaller
          run: pyinstaller --clean main.spec --distpath "./Myth Mod Manager"
        
        - name: Tar Myth Mod Manager
          run: tar -czvf Myth-Mod-Manager.tar.gz "./Myth Mod Manager/"

        - name: Upload Myth Mod Manager to Latest Release Assets
          uses: softprops/action-gh-release@v2
          if: startsWith(github.ref, 'refs/tags/')
          with:
            files: Myth-Mod-Manager.tar.gz