
name: Build into Executables And Release

on:
  release:
    types: [published]
  workflow_dispatch:
  
jobs:
  BuildAndUploadToReleaseAssets:
    permissions:
        contents: write
    runs-on: windows-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v4
         
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: 3.11

        - name: Install Requirements
          run: pip install -r requirements.txt
        
        - name: Update Translation Binaries
          run: |
            dir .\src\lang
            .\utils\update_qm_files.py
            dir .\src\lang
