
name: Build into Executables And Release

on:
  release:
    types: [published]
  workflow_dispatch:
  
jobs:
  BuildAndUploadToReleaseAssets:
    permissions:
        contents: write
    runs-on: windows-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v4
         
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: 3.11

        - name: Install Requirements
          run: pip install -r requirements.txt
        
        - name: Update Translation Binaries
          run: .\utils\update_qm_files.py
        
        - name: Build with PyInstaller
          run: pyinstaller --clean main.spec --distpath "./Myth Mod Manager"
        
        - name: Zip Myth Mod Manager
          run: tar -a -c -f Myth-Mod-Manager.zip "Myth Mod Manager/Myth Mod Manager.exe"
